import { existsSync, mkdirSync, readFileSync, renameSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

/** Versioned product-managed MCP catalog written into the app's DSH_HOME. */
export const EMBEDDED_MCP_CONFIG_VERSION = 1
export const MCP_MANAGED_PATCH_BEGIN = '# BEGIN FREECODE MANAGED MCP'
export const MCP_MANAGED_PATCH_END = '# END FREECODE MANAGED MCP'

const PROCESS_CWD = '$process.cwd'

const SERVER_DEFINITIONS = [
  {
    id: 'serena',
    serverName: 'serena',
    transport: 'stdio',
    command: 'uvx',
    args: ['--from', 'git+https://github.com/oraios/serena', 'serena', 'start-mcp-server', '--context', 'ide-assistant', '--project-from-cwd'],
    cwd: PROCESS_CWD,
  },
  {
    id: 'lsp-typescript',
    serverName: 'lsp-typescript',
    transport: 'stdio',
    command: 'mcp-language-server',
    args: ['--workspace', PROCESS_CWD, '--lsp', 'typescript-language-server', '--', '--stdio'],
    cwd: PROCESS_CWD,
  },
  {
    id: 'lsp-python',
    serverName: 'lsp-python',
    transport: 'stdio',
    command: 'mcp-language-server',
    args: ['--workspace', PROCESS_CWD, '--lsp', 'pyright-langserver', '--', '--stdio'],
    cwd: PROCESS_CWD,
  },
] as const

interface ManagedMcpServer {
  id: string
  serverName: string
  transport: 'stdio'
  command: string
  args: readonly string[]
  cwd: string
}

interface EmbeddedMcpConfig {
  version: number
  servers: Array<ManagedMcpServer & { enabled: boolean }>
}

export interface EmbeddedMcpState {
  configPath: string
  patchPath: string
  enabled: string[]
}

function defaultConfig(): EmbeddedMcpConfig {
  return {
    version: EMBEDDED_MCP_CONFIG_VERSION,
    servers: SERVER_DEFINITIONS.map((server) => ({ ...server, enabled: true })),
  }
}

function readConfig(path: string): EmbeddedMcpConfig {
  if (!existsSync(path)) return defaultConfig()
  try {
    const raw = JSON.parse(readFileSync(path, 'utf8')) as {
      version?: unknown
      servers?: unknown
    }
    const flags = new Map(
      Array.isArray(raw.servers)
        ? raw.servers
          .filter((server): server is { id: string, enabled: boolean } => (
            typeof server === 'object' && server !== null
            && typeof (server as { id?: unknown }).id === 'string'
            && typeof (server as { enabled?: unknown }).enabled === 'boolean'
          ))
          .map((server) => [server.id, server.enabled] as const)
        : [],
    )
    return {
      version: EMBEDDED_MCP_CONFIG_VERSION,
      servers: SERVER_DEFINITIONS.map((server) => ({
        ...server,
        enabled: flags.get(server.id) ?? true,
      })),
    }
  } catch {
    // Preserve a malformed file before recovering to the safe, enabled catalog.
    const backup = `${path}.invalid-${Date.now()}`
    try { renameSync(path, backup) } catch { /* startup must remain available */ }
    return defaultConfig()
  }
}

function yamlValue(value: string): string {
  return value === PROCESS_CWD ? '!!js process.cwd()' : JSON.stringify(value)
}

function renderManagedPatch(config: EmbeddedMcpConfig): string {
  const lines = [
    MCP_MANAGED_PATCH_BEGIN,
    '# Generated by FreeCode. Edit mcp/servers.json to toggle entries.',
    '# The MCP client bridge is bundled; external server executables are optional prerequisites.',
  ]
  for (const server of config.servers) {
    lines.push(
      `- id: ${JSON.stringify(`freecode-mcp-${server.id}`)}`,
      '  name: "@deepseek-ai/dsh-mcp-client"',
      `  disabled: ${server.enabled ? 'false' : 'true'}`,
      '  config:',
      `    transport: ${JSON.stringify(server.transport)}`,
      `    serverName: ${JSON.stringify(server.serverName)}`,
      `    command: ${JSON.stringify(server.command)}`,
      `    args: [${server.args.map(yamlValue).join(', ')}]`,
      `    cwd: ${yamlValue(server.cwd)}`,
      '    failOnStartupError: false',
      '    reconnect:',
      '      enabled: true',
      '      initialDelayMs: 500',
      '      maxDelayMs: 30000',
      '      maxAttempts: 10',
    )
  }
  lines.push(MCP_MANAGED_PATCH_END)
  return `${lines.join('\n')}\n`
}

function mergeManagedPatch(existing: string, generated: string): string {
  const block = new RegExp(`${MCP_MANAGED_PATCH_BEGIN}[\\s\\S]*?${MCP_MANAGED_PATCH_END}\\r?\\n?`, 'm')
  const normalized = generated.endsWith('\n') ? generated : `${generated}\n`
  if (block.test(existing)) return existing.replace(block, normalized)
  const prefix = existing.trimEnd()
  return prefix.length === 0 ? normalized : `${prefix}\n\n${normalized}`
}

function writeAtomic(path: string, contents: string): void {
  const temporary = `${path}.tmp-${process.pid}-${Date.now()}`
  writeFileSync(temporary, contents, { encoding: 'utf8', mode: 0o600 })
  renameSync(temporary, path)
}

/**
 * Materialize the bundled MCP catalog on first boot and refresh only the
 * FreeCode-managed overlay on later boots. User patch rows remain untouched.
 */
export function ensureEmbeddedMcpConfig(homeDir: string): EmbeddedMcpState {
  const configDir = join(homeDir, 'mcp')
  const configPath = join(configDir, 'servers.json')
  const patchPath = join(homeDir, 'cordis.patch.yml')
  mkdirSync(configDir, { recursive: true })
  const config = readConfig(configPath)
  writeAtomic(configPath, `${JSON.stringify(config, null, 2)}\n`)
  const existingPatch = existsSync(patchPath) ? readFileSync(patchPath, 'utf8') : ''
  writeAtomic(patchPath, mergeManagedPatch(existingPatch, renderManagedPatch(config)))
  return {
    configPath,
    patchPath,
    enabled: config.servers.filter((server) => server.enabled).map((server) => server.id),
  }
}
