/**
 * Built-in MCP catalog and deterministic DSH patch rendering.
 *
 * The catalog deliberately contains commands that are actually published:
 * Serena is installed through its official uv entry point and the LSP bridge
 * is the Go project maintained at isaacphi/mcp-language-server. The old
 * release used two nonexistent npm package names and generated duplicate
 * `mcp-client` YAML keys, so the runtime silently ignored most of the setup.
 */

export const MCP_CONFIG_VERSION = 1;
export const PROCESS_CWD = '$process.cwd';
export const MANAGED_PATCH_BEGIN = '# BEGIN FREECODE MANAGED MCP';
export const MANAGED_PATCH_END = '# END FREECODE MANAGED MCP';

export const MCP_SERVER_DEFINITIONS = Object.freeze([
  {
    id: 'serena',
    description: 'Serena semantic retrieval and structural editing',
    transport: 'stdio',
    serverName: 'serena',
    command: 'uvx',
    args: ['--from', 'git+https://github.com/oraios/serena', 'serena', 'start-mcp-server', '--context', 'ide-assistant', '--project-from-cwd'],
    cwd: PROCESS_CWD,
    install: {
      command: 'uvx',
      args: ['--from', 'git+https://github.com/oraios/serena', 'serena', '--help'],
      prerequisite: 'uvx (install uv from https://docs.astral.sh/uv/)',
    },
  },
  {
    id: 'lsp-typescript',
    description: 'LSP semantic tools for TypeScript and JavaScript',
    transport: 'stdio',
    serverName: 'lsp-typescript',
    command: 'mcp-language-server',
    args: ['--workspace', PROCESS_CWD, '--lsp', 'typescript-language-server', '--', '--stdio'],
    cwd: PROCESS_CWD,
    install: {
      command: 'go',
      args: ['install', 'github.com/isaacphi/mcp-language-server@latest'],
      prerequisite: 'Go plus the npm TypeScript language server (npm install --global typescript typescript-language-server)',
    },
  },
  {
    id: 'lsp-python',
    description: 'LSP semantic tools for Python',
    transport: 'stdio',
    serverName: 'lsp-python',
    command: 'mcp-language-server',
    args: ['--workspace', PROCESS_CWD, '--lsp', 'pyright-langserver', '--', '--stdio'],
    cwd: PROCESS_CWD,
    install: {
      command: 'go',
      args: ['install', 'github.com/isaacphi/mcp-language-server@latest'],
      prerequisite: 'Go plus the npm Python language server (npm install --global pyright)',
    },
  },
]);

export function defaultMcpConfig() {
  return {
    version: MCP_CONFIG_VERSION,
    servers: MCP_SERVER_DEFINITIONS.map(({ install: _install, ...server }) => ({
      ...server,
      enabled: true,
    })),
  };
}

function isRecord(value) {
  return value !== null && typeof value === 'object' && !Array.isArray(value);
}

/** Preserve only the user-controlled enable flags; executable definitions stay pinned. */
export function mergeMcpConfig(raw) {
  const defaults = defaultMcpConfig();
  const previous = isRecord(raw) && Array.isArray(raw.servers) ? raw.servers : [];
  const enabledById = new Map(
    previous
      .filter((server) => isRecord(server) && typeof server.id === 'string' && typeof server.enabled === 'boolean')
      .map((server) => [server.id, server.enabled]),
  );
  return {
    version: MCP_CONFIG_VERSION,
    servers: defaults.servers.map((server) => ({
      ...server,
      enabled: enabledById.get(server.id) ?? true,
    })),
  };
}

function yamlScalar(value) {
  return JSON.stringify(String(value));
}

function renderArg(value) {
  return value === PROCESS_CWD ? '!!js process.cwd()' : yamlScalar(value);
}

/** Render a valid patch list: one unique plugin row per MCP server. */
export function renderMcpPatch(config) {
  const lines = [
    MANAGED_PATCH_BEGIN,
    '# Generated by FreeCode. Edit mcp/servers.json to toggle entries.',
    '# The client bridge is bundled; server processes are installed separately by setup:mcp.',
  ];
  for (const server of config.servers) {
    lines.push(
      `- id: ${yamlScalar(`freecode-mcp-${server.id}`)}`,
      '  name: "@deepseek-ai/dsh-mcp-client"',
      `  disabled: ${server.enabled ? 'false' : 'true'}`,
      '  config:',
      `    transport: ${yamlScalar(server.transport)}`,
      `    serverName: ${yamlScalar(server.serverName)}`,
      `    command: ${yamlScalar(server.command)}`,
      `    args: [${server.args.map(renderArg).join(', ')}]`,
      `    cwd: ${renderArg(server.cwd)}`,
      '    failOnStartupError: false',
      '    reconnect:',
      '      enabled: true',
      '      initialDelayMs: 500',
      '      maxDelayMs: 30000',
      '      maxAttempts: 10',
    );
  }
  lines.push(MANAGED_PATCH_END);
  return `${lines.join('\n')}\n`;
}

/** Replace only FreeCode's managed block and preserve unrelated user patches. */
export function mergeManagedPatch(existing, generated) {
  const source = typeof existing === 'string' ? existing : '';
  const block = new RegExp(`${MANAGED_PATCH_BEGIN}[\\s\\S]*?${MANAGED_PATCH_END}\\r?\\n?`, 'm');
  const normalized = generated.endsWith('\n') ? generated : `${generated}\n`;
  if (block.test(source)) return source.replace(block, normalized);
  const prefix = source.trimEnd();
  return prefix.length === 0 ? normalized : `${prefix}\n\n${normalized}`;
}

export function validateMcpConfig(config) {
  if (!isRecord(config) || config.version !== MCP_CONFIG_VERSION || !Array.isArray(config.servers)) {
    throw new Error(`MCP config must have version ${MCP_CONFIG_VERSION} and a servers array`);
  }
  const ids = new Set();
  for (const server of config.servers) {
    if (!isRecord(server) || typeof server.id !== 'string' || ids.has(server.id)) {
      throw new Error('MCP config contains a missing or duplicate server id');
    }
    if (typeof server.enabled !== 'boolean') throw new Error(`MCP server ${server.id} needs boolean enabled`);
    ids.add(server.id);
  }
  return config;
}
